from __future__ import annotations

from typing import Any, Mapping, Sequence


# PyJWT-style: InvalidTokenError is the base for token handling errors; DecodeError
# and others nest under it; InvalidSignatureError nests under DecodeError.
class OxyJWTError(Exception): ...
class InvalidTokenError(OxyJWTError): ...
class DecodeError(InvalidTokenError): ...
class InvalidSignatureError(DecodeError): ...
class ExpiredSignatureError(InvalidTokenError): ...
class ImmatureSignatureError(InvalidTokenError): ...
class InvalidAudienceError(InvalidTokenError): ...
class InvalidIssuerError(InvalidTokenError): ...
class InvalidSubjectError(InvalidTokenError): ...
class InvalidAlgorithmError(InvalidTokenError): ...
class InvalidIssuedAtError(InvalidTokenError): ...
class MissingRequiredClaimError(InvalidTokenError): ...
class EncodeError(OxyJWTError): ...
class InvalidKeyError(OxyJWTError): ...


class EncodingKey:
    @staticmethod
    def from_secret(secret: str | bytes) -> EncodingKey: ...
    @staticmethod
    def from_rsa_pem(pem: str | bytes) -> EncodingKey: ...
    @staticmethod
    def from_ec_pem(pem: str | bytes) -> EncodingKey: ...
    @staticmethod
    def from_ed_pem(pem: str | bytes) -> EncodingKey: ...


class DecodingKey:
    @staticmethod
    def from_secret(secret: str | bytes) -> DecodingKey: ...
    @staticmethod
    def from_rsa_pem(pem: str | bytes) -> DecodingKey: ...
    @staticmethod
    def from_ec_pem(pem: str | bytes) -> DecodingKey: ...
    @staticmethod
    def from_ed_pem(pem: str | bytes) -> DecodingKey: ...
    @staticmethod
    def from_jwk(jwk: str | Mapping[str, Any]) -> DecodingKey: ...


def encode(
    payload: Mapping[str, Any],
    key: str | bytes | EncodingKey,
    algorithm: str = "HS256",
    headers: Mapping[str, Any] | None = None,
) -> str: ...


def encode_json(
    payload_json: str,
    key: str | bytes | EncodingKey,
    algorithm: str = "HS256",
    headers: Mapping[str, Any] | None = None,
) -> str: ...


def decode(
    token: str,
    key: str | bytes | DecodingKey,
    algorithms: Sequence[str],
    *,
    audience: str | Sequence[str] | None = None,
    issuer: str | Sequence[str] | None = None,
    subject: str | None = None,
    leeway: float = 0.0,
    options: Mapping[str, Any] | None = None,
    require: Sequence[str] | None = None,
) -> dict[str, Any]: ...


def jws_parse_compact(
    token: str,
) -> tuple[bytes, dict[str, Any], bytes, bytes]: ...


def get_unverified_header(token: str) -> dict[str, Any]: ...
def decode_unverified(token: str) -> dict[str, Any]: ...
