from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from oxyjwt._oxyjwt import DecodingKey

class PyJWK:
    key: DecodingKey
    def __init__(
        self, jwk: Mapping[str, Any] | str, algorithm: str | None = None
    ) -> None: ...
    @staticmethod
    def from_dict(obj: Mapping[str, Any], algorithm: str | None = None) -> PyJWK: ...
    @staticmethod
    def from_json(data: str, algorithm: str | None = None) -> PyJWK: ...
    @property
    def key_type(self) -> str | None: ...
    @property
    def key_id(self) -> str | None: ...
    @property
    def public_key_use(self) -> str | None: ...

class PyJWKSet:
    keys: list[PyJWK]
    def __init__(self, keys: list[dict[str, Any]]) -> None: ...
    @staticmethod
    def from_dict(obj: dict[str, Any]) -> PyJWKSet: ...
    @staticmethod
    def from_json(data: str) -> PyJWKSet: ...
    def __getitem__(self, kid: str) -> PyJWK: ...
