from oxyjwt._oxyjwt import OxyJWTError

class PyJWKError(OxyJWTError): ...
class PyJWKSetError(OxyJWTError): ...
class PyJWKClientError(OxyJWTError): ...
class PyJWKClientConnectionError(PyJWKClientError): ...
